#!/bin/bash
set -e

cd "$(dirname "$0")"

# Skip WASM build in CI — pre-built files are committed in public/wasm/
if ! command -v wasm-pack &> /dev/null; then
  echo "wasm-pack not found, skipping WASM build (using pre-built files)"
  exit 0
fi

wasm-pack build \
  --target no-modules \
  --out-dir ../../public/wasm \
  --release \
  --no-typescript

# Clean up unnecessary files generated by wasm-pack
rm -f ../../public/wasm/.gitignore
rm -f ../../public/wasm/package.json

echo "WASM built to packages/web/public/wasm/"
